name: install-Test

on:
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      #- name: instalação do ffmpeg
       # run: |
        #  sudo apt update --yes
         # sudo apt install ffmpeg --yes

      - name: Setup FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1          

      - name: Executar FFMPEG
        run: |
          ffmpeg --help
